Traceback (most recent call last):
  File "/home/madan/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/madan/.local/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/madan/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/madan/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/madan/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/madan/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import pandas as pdb
import matplotlib.pyplot as plt
from lmfit import Model
%matplotlib inline
------------------

----- stderr -----

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/madan/.local/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/home/madan/.local/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 456, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/usr/lib/python3/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_363360/44817807.py", line 2, in <module>
    import pandas as pdb
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
----- stderr -----

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/madan/.local/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/home/madan/.local/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 456, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/usr/lib/python3/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_363360/44817807.py", line 2, in <module>
    import pandas as pdb
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/arrays/arrow/array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/arrays/masked.py", line 60, in <module>
    from pandas.core import (
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/home/madan/.local/lib/python3.10/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3/dist-packages/bottleneck/__init__.py", line 2, in <module>
    from .reduce import (
----- stderr -----

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/madan/.local/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/home/madan/.local/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 456, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/madan/.local/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2914, in run_cell
    result = self._run_cell(
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2960, in _run_cell
    return runner(coro)
  File "/usr/lib/python3/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3185, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3377, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_363360/44817807.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/usr/lib/python3/dist-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/usr/lib/python3/dist-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/usr/lib/python3/dist-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/usr/lib/python3/dist-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/usr/lib/python3/dist-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_363360/44817807.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpdb[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;32mfrom[0m [0mlmfit[0m [0;32mimport[0m [0mModel[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mget_ipython[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mrun_line_magic[0m[0;34m([0m[0;34m'matplotlib'[0m[0;34m,[0m [0;34m'inline'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3/dist-packages/matplotlib/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m    107[0m [0;31m# cbook must import matplotlib only within function[0m[0;34m[0m[0;34m[0m[0m
[1;32m    108[0m [0;31m# definitions, so it is safe to import from it here.[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 109[0;31m [0;32mfrom[0m [0;34m.[0m [0;32mimport[0m [0m_api[0m[0;34m,[0m [0m_version[0m[0;34m,[0m [0mcbook[0m[0;34m,[0m [0mdocstring[0m[0;34m,[0m [0mrcsetup[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    110[0m [0;32mfrom[0m [0mmatplotlib[0m[0;34m.[0m[0mcbook[0m [0;32mimport[0m [0mMatplotlibDeprecationWarning[0m[0;34m,[0m [0msanitize_sequence[0m[0;34m[0m[0;34m[0m[0m
[1;32m    111[0m [0;32mfrom[0m [0mmatplotlib[0m[0;34m.[0m[0mcbook[0m [0;32mimport[0m [0mmplDeprecation[0m  [0;31m# deprecated[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3/dist-packages/matplotlib/rcsetup.py[0m in [0;36m<module>[0;34m[0m
[1;32m     25[0m [0;32mfrom[0m [0mmatplotlib[0m [0;32mimport[0m [0m_api[0m[0;34m,[0m [0mcbook[0m[0;34m[0m[0;34m[0m[0m
[1;32m     26[0m [0;32mfrom[0m [0mmatplotlib[0m[0;34m.[0m[0mcbook[0m [0;32mimport[0m [0mls_mapper[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 27[0;31m [0;32mfrom[0m [0mmatplotlib[0m[0;34m.[0m[0mcolors[0m [0;32mimport[0m [0mColormap[0m[0;34m,[0m [0mis_color_like[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     28[0m [0;32mfrom[0m [0mmatplotlib[0m[0;34m.[0m[0mfontconfig_pattern[0m [0;32mimport[0m [0mparse_fontconfig_pattern[0m[0;34m[0m[0;34m[0m[0m
[1;32m     29[0m [0;32mfrom[0m [0mmatplotlib[0m[0;34m.[0m[0m_enums[0m [0;32mimport[0m [0mJoinStyle[0m[0;34m,[0m [0mCapStyle[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3/dist-packages/matplotlib/colors.py[0m in [0;36m<module>[0;34m[0m
[1;32m     54[0m [0;32mimport[0m [0mmatplotlib[0m [0;32mas[0m [0mmpl[0m[0;34m[0m[0;34m[0m[0m
[1;32m     55[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 56[0;31m [0;32mfrom[0m [0mmatplotlib[0m [0;32mimport[0m [0m_api[0m[0;34m,[0m [0mcbook[0m[0;34m,[0m [0mscale[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     57[0m [0;32mfrom[0m [0;34m.[0m[0m_color_data[0m [0;32mimport[0m [0mBASE_COLORS[0m[0;34m,[0m [0mTABLEAU_COLORS[0m[0;34m,[0m [0mCSS4_COLORS[0m[0;34m,[0m [0mXKCD_COLORS[0m[0;34m[0m[0;34m[0m[0m
[1;32m     58[0m [0;34m[0m[0m

[0;32m/usr/lib/python3/dist-packages/matplotlib/scale.py[0m in [0;36m<module>[0;34m[0m
[1;32m     21[0m [0;32mimport[0m [0mmatplotlib[0m [0;32mas[0m [0mmpl[0m[0;34m[0m[0;34m[0m[0m
[1;32m     22[0m [0;32mfrom[0m [0mmatplotlib[0m [0;32mimport[0m [0m_api[0m[0;34m,[0m [0mdocstring[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 23[0;31m from matplotlib.ticker import (
[0m[1;32m     24[0m     [0mNullFormatter[0m[0;34m,[0m [0mScalarFormatter[0m[0;34m,[0m [0mLogFormatterSciNotation[0m[0;34m,[0m [0mLogitFormatter[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     25[0m     [0mNullLocator[0m[0;34m,[0m [0mLogLocator[0m[0;34m,[0m [0mAutoLocator[0m[0;34m,[0m [0mAutoMinorLocator[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3/dist-packages/matplotlib/ticker.py[0m in [0;36m<module>[0;34m[0m
[1;32m    134[0m [0;32mimport[0m [0mmatplotlib[0m [0;32mas[0m [0mmpl[0m[0;34m[0m[0;34m[0m[0m
[1;32m    135[0m [0;32mfrom[0m [0mmatplotlib[0m [0;32mimport[0m [0m_api[0m[0;34m,[0m [0mcbook[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 136[0;31m [0;32mfrom[0m [0mmatplotlib[0m [0;32mimport[0m [0mtransforms[0m [0;32mas[0m [0mmtransforms[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    137[0m [0;34m[0m[0m
[1;32m    138[0m [0m_log[0m [0;34m=[0m [0mlogging[0m[0;34m.[0m[0mgetLogger[0m[0;34m([0m[0m__name__[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3/dist-packages/matplotlib/transforms.py[0m in [0;36m<module>[0;34m[0m
[1;32m     44[0m [0;34m[0m[0m
[1;32m     45[0m [0;32mfrom[0m [0mmatplotlib[0m [0;32mimport[0m [0m_api[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 46[0;31m from matplotlib._path import (
[0m[1;32m     47[0m     affine_transform, count_bboxes_overlapping_bbox, update_path_extents)
[1;32m     48[0m [0;32mfrom[0m [0;34m.[0m[0mpath[0m [0;32mimport[0m [0mPath[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: numpy.core.multiarray failed to import

